# ============================================================
# Atlassian API Test Configuration
# ============================================================

# Base URL for all API requests
base.url=https://parusonly.atlassian.net

# Basic Auth Credentials
# Replace with your actual Atlassian username (email) and API token
auth.username=Parusonly@gmail.com
auth.password=ATATT3xFfGF0zTvLDlvUT18WpOtxiAtnqyEDGDpLM3yyTtsE8x5vyp0n6JyS68QOXOcU5IC83BNY1A2pzzxhBhr_nMnS7rFZ9A52hFMNhMfT3A_dpzQPKixq5w_dMnqIgvBLbmCPlR8KeL1tpxVysgW4vNUbd3xWlJhZNwr78aUJ990hCFaQl0g=BADCEB90
